### ISSUE TITLE
go-pluginserver process cost too much CPU resource!

### ISSUE THREAD

**Issue by hhofchina** [Kong/go-pluginserver#24]
When I benchmark test kong with go plugin go-hello , go-pluginserver cost almost all CPU resource !! QPS with go-hello only half of no plugin

**Comment by hhofchina** [comment]
(pprof) top 10
Showing nodes accounting for 5.27mins, 88.89% of 5.93mins total
Dropped 468 nodes (cum <= 0.03mins)
Showing top 10 nodes out of 107
      flat  flat%   sum%        cum   cum%
  2.01mins 33.92% 33.92%   2.01mins 33.92%  runtime.pthread_cond_signal
  1.14mins 19.17% 53.09%   1.14mins 19.19%  runtime.pthread_cond_wait
  0.98mins 16.45% 69.54%   1.01mins 17.04%  syscall.syscall
  0.30mins  5.12% 74.66%   0.30mins  5.14%  runtime.kevent
  0.26mins  4.43% 79.09%   0.26mins  4.43%  runtime.gorecover
  0.20mins  3.37% 82.46%   1.10mins 18.54%  net/rpc.(*service).call
  0.12mins  2.07% 84.54%   0.49mins  8.31%  github.com/ugorji/go/codec.(*Decoder).Decode
  0.12mins  1.97% 86.50%   0.42mins  7.12%  runtime.netpoll
  0.09mins  1.56% 88.06%   0.09mins  1.57%  runtime.usleep
  0.05mins  0.83% 88.89%   0.05mins  0.89%  runtime.step

**Comment by hhofchina** [comment]
LOCK need to be improve

**Comment by ealogar** [comment]
If you reduce the use of the kong object to the minimal expresion this is improved. Every time the kong object is accessed to get a header, to set a query event to write a simple log a two way message rpc is travelling an consuming cpu....
I have also i

**Comment by primableatom** [comment]
@ealogar What are your thoughts on running go plugins in production. I just finished writing a plugin in go and soon will be deploying it Heroku and I am concerned about the kong calls too. I chose go over lua because of the available libraries and eco system in general but if there is a CPU hog then this should have been mentioned in the docs.

**Comment by ealogar** [comment]
@primableatom  What I can tell you is that we have increased the cpu of the containers running kong 120% to be able to cope with go; the cpu is consumed mainly in the messages interchange
I have tested that if you do not write logs and just to what is needed with kong the cpu is reduced, but a simple kong.Log increase cpu usage.
Another thing is that you can only run plugins in go if they do not change configuration from the initial setup, otherwise as the reload event is not propagated it won't take effect

**Comment by gszr** [comment]
@hhofchina @ealogar Are you able to provide me with the config to repro this issue? I will be looking into it!

**Comment by javierguerragiraldez** [comment]
@ealogar is correct, most of the overhead is the IPC between Kong and the Go process, and this happens for every event and PDK call.

@hhofchina in my tests, when adding the CPU of all nginx processes, it's usually around 3x that of Go.  The go process rises to the top because it's a single multithreaded process, while nginx is many single-threaded workers, so it doesn't stand out so much.

If you're seeing something different, please tell.

**Comment by javierguerragiraldez** [comment]
Closing for lack of feedback
