### ISSUE TITLE
Feature request - some kind of the "hook" before shutdown

### ISSUE THREAD

**Issue by matviienko** [Kong/go-pluginserver#36]
As part of this feature request we would like to see some kind of the "hook" function or callback that is going to be executed before shutdown of the kong (go-pluginserver) that we can program as we need. For instance if we need to open pool of connections to external database and gracefully close them on this hook before we shutdown application.

**Comment by javierguerragiraldez** [comment]
This is unlikely to ever be implemented.  Since the pluginserver can host plugins of different origins in the same process space, any of these must be prepared to crash at any moment and operate normally.   Even if we use OS facilities like signal trapping, there's no guarantee that the Go runtime is in any valid state during an unexpected shutdown.

In the case of databases, all ACID-capable servers are prepared to efficiently ROLLBACK any open transaction on unexpectedly-closed connections.  Just be sure to COMMIT transactions when they're ready, and it's OK to keep open connections that could be killed at any time.
